services:
    _defaults: { public: false, autowire: true, autoconfigure: true }
    Gekomod\ExtensionsBundle\Controller\:
        resource: '%kernel.project_dir%/vendor/gekomod/extensions-bundle/Controller'
        autowire: true
        tags: ['controller.service_arguments']
    admin.extensions:
        class: Gekomod\ExtensionsBundle\Admin\ExtensionsAdmin
        tags:
            - { name:  sonata.admin, manager_type: orm, group: Ustawienia, label: Extensions}
        arguments:
            - null
            - null
            - Gekomod\ExtensionsBundle\Controller\ExtensionsCRUDController
        public: true